version: "3"
services:
  cassandra:
    image: cassandra:3.11.2
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
  postgres:
    image: docker-hub.2gis.ru/postgres:9.6.8-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: BroadwayDataProjection
    volumes:
      - ./projections-db-schema.sql:/docker-entrypoint-initdb.d/projections-db-schema.sql:ro
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
